ProductsPage_Objects:
  SortProducts:
    LocatorStrategy: WithAttribute
    ElementType: select
    Attribute: data-test
    Name: product_sort_container
  SortProductsActiveOption:
    LocatorStrategy: ParentReferenceWithAttribute
    ParentReference: SortProducts
    UseRelation: True
    Relation: parent
    RelationElementType: span
    ElementType: span
    Attribute: class
    Name: active_option
  InventoryList:
    LocatorStrategy: WithAttribute
    ElementType: div
    Attribute: class
    Name: inventory_list
  InventoryItem:
    LocatorStrategy: ParentReferenceWithAttribute
    ParentReference: InventoryList
    ElementType: div
    Attribute: class
    Name: inventory_item
  InventoryItemImage:
    LocatorStrategy: ParentReferenceWithAttribute
    ParentReference: InventoryItem
    ElementType: div
    Attribute: class
    Name: inventory_item_img
  InventoryItemImageLink:
    LocatorStrategy: ParentReferenceWithType
    ParentReference: InventoryItemImage
    ElementType: a
  InventoryItemName:
    LocatorStrategy: ParentReferenceWithAttribute
    ParentReference: InventoryItem
    ElementType: div
    Attribute: class
    Name: inventory_item_name
  InventoryItemPrices:
    LocatorStrategy: ParentReferenceWithAttribute
    ParentReference: InventoryItem
    ElementType: div
    Attribute: class
    Name: inventory_item_price
  InventoryAddToCart:
    LocatorStrategy: ParentReferenceWithText
    ParentReference: InventoryItem
    ElementType: button
    Text: Add to cart
  ShoppingCart:
    LocatorStrategy: WithAttribute
    ElementType: span
    Attribute: class
    Name: shopping_cart_badge


