ProductsPage_Definitions:
  InventoryItemName:
    MultipleElements: True
    ElementCountShouldBe: 6
    ElementsShouldContain:
      - Sauce Labs Backpack
      - Sauce Labs Bike Light
      - Sauce Labs Bolt T-Shirt
      - Sauce Labs Fleece Jacket
      - Sauce Labs Onesie
      - Test.allTheThings() T-Shirt (Red)
  InventoryItemImageLink:
    MultipleElements: True
    ElementCountShouldBe: 6
  