stages:
    - test

Robot UI Tests:
    stage: test 
    image: python:3.10.0a6-buster
    when: always
    script:
        - chmod +x ./pipeline_setup_rf_env.sh
        - ./pipeline_setup_rf_env.sh
        - robot -v headless:True -d Tests/Reports --xunit Reports .
    artifacts:
        when: always
        expire_in: 1 week
        paths:
            - /builds/matthewking182/robot-framework-swaglabs/Tests/Reports/output.xml
            - /builds/matthewking182/robot-framework-swaglabs/Tests/Reports/Reports.xml
            - /builds/matthewking182/robot-framework-swaglabs/Tests/Reports/report.html
            - /builds/matthewking182/robot-framework-swaglabs/Tests/Reports/log.html
        reports:
            junit:
                - /builds/matthewking182/robot-framework-swaglabs/Tests/Reports/Reports.xml

Gatling Performance Tests:
    when: always
    stage: test 
    image: maven:3.8.4-jdk-8
    script:
        - chmod +x ./pipeline_setup_gatling.sh
        - ./pipeline_setup_gatling.sh
        - GATLING_HOME="${PWD}/gatling-charts-highcharts-bundle-3.7.6" && echo ${GATLING_HOME}
        - cd ./Performance 
        - mvn gatling:test -Dgatling.continueOnAssertionFailure=true -Dgatling.runMultipleSimulations=true
    after_script:
        - echo ${PWD}
        - mkdir GatlingReports
        - mkdir JUnit
        - mv -v /builds/matthewking182/robot-framework-swaglabs/Performance/target/gatling/* ./GatlingReports
        - find ./GatlingReports -name 'assertions.xml' -exec sh -c 'md5=$(md5sum < "$0") && md5=${md5%% *}.xml && cp "$0" "./JUnit/$md5"' {} \;
    artifacts:
        when: always
        expire_in: 1 week
        paths:
            - /builds/matthewking182/robot-framework-swaglabs/GatlingReports/*
            - /builds/matthewking182/robot-framework-swaglabs/JUnit/*
        reports:
            junit:
                - /builds/matthewking182/robot-framework-swaglabs/JUnit/*